### PR TITLE
Add Nuxt top-level option

### LINKED ISSUE #132: [Nuxt] Support top level option
Hi,
Would it be possible to support top-level option as well as module option in Nuxt ?
This would be much cleaner for people that have a lot of Nuxt module.
https://nuxtjs.org/docs/2.x/directory-structure/modules/

Currently I have to set options like so:
```
modules: [
    ['vue-sweetalert2/nuxt', {
            customClass: {
            container: 'theme-custom',
            confirmButton: 'button primary',
            cancelButton: 'button secondary'
        },
        buttonsStyling: false
    }],
],
```
And with top-level options we could do something like this:
```
modules: [
    'vue-sweetalert2/nuxt'
],

sweetalert: {
    customClass: {
        container: 'theme-custom',
        confirmButton: 'button primary',
        cancelButton: 'button secondary'
    },
    buttonsStyling: false
}
```

## I also want to know

  - Version: 4.2.1
  - Platform: macOS
  - Subsystem: 11.1

### PR DESCRIPTION
**Pull request by mrleblanc101**
Fix #132

### CODE REVIEW

**Comment by mrleblanc101** [comment]
I don't understand the error: `/home/runner/work/_temp/ce7d307c-2b8c-4211-81b6-7c3eb9a697ce.sh: line 1: cd: packages/vue-sweetalert2: No such file or directory`. Test work on my machine.

**Comment by avil13** [comment]
@mrleblanc101 
I fixed the github action and could you make edits in the `packages/vue-sweetalert2/nuxt/no-css.js` file as well?

**Comment by mrleblanc101** [comment]
@avil13 You are right ! I thought the logic was handled in the module, not that they were 2 different module.

**Comment by mrleblanc101** [comment]
Thanks 😄 
Just let me know when a new version is available on npm if you don't have time to publish on right away !

**Comment by avil13** [comment]
Version 4.3.1 with minor updates to the packages

**Pull request merged**
